<?php
/** Defaults */
// WP-REST NAMESPACE
defined('HWPGROSSMANN_REST_NAMESPACE') ||define('HWPGROSSMANN_REST_NAMESPACE','hwpgrossmann/v2');


/** Status Codes */
// 2xx
defined('HWPGROSSMANN_STATUS_OKAY') || define('HWPGROSSMANN_STATUS_OKAY',200);

// 4xx
defined('HWPGROSSMANN_STATUS_BAD_REQUEST') || define('HWPGROSSMANN_STATUS_BAD_REQUEST',400);
defined('HWPGROSSMANN_STATUS_NOT_AUTHORIZED') || define('HWPGROSSMANN_STATUS_NOT_AUTHORIZED',401);
defined('HWPGROSSMANN_STATUS_NOT_FOUND') || define('HWPGROSSMANN_STATUS_NOT_FOUND',404);